### ISSUE TITLE
Does not report error if the DRBD split brain file does not exist

### ISSUE THREAD

**Issue by diegoakechi** [ClusterLabs/ha_cluster_exporter#107]
The exporter is reporting error because the split-brain directory does not exist

```
Dec 06 13:14:11 vmdrbd01 ha_cluster_exporter[32008]: time="2019-12-06T13:14:11Z" level=warning msg="Error while reading directory /var/run/drbd/splitbrain: open /var/run/drbd/splitbrain: no such file or directory"
```

As this means that there is no split-brain, it should not be reported. If the file exists, this should be logged and should also explain that the sysadmin needs to remove the file after threating the split-brain.

**Comment by stefanotorresi** [comment]
To be precise this is not about a file, it's about the directory that will contain the hook messages. We assumed the directory existed, before looking for files in it.

**Comment by MalloZup** [comment]
closing fixed by pr in review
