### ISSUE TITLE
DRBD  on Debian 10 buster, DRBD is at version 9.5.0. doesn't work 

### ISSUE THREAD

**Issue by kilida2020** [ClusterLabs/ha_cluster_exporter#141]
Olá,
Ao tentar coletar as informações do DRBD apresenta erro. Alguém pode ajudar?

INFO[0000] Using config file: /home/master/ha_cluster_exporter/ha_cluster_exporter.yaml
WARN[0000] could not initialize Pacemaker collector: '/usr/sbin/crm_mon' does not exist
WARN[0000] could not initialize Corosync collector: '/usr/sbin/corosync-cfgtool' does not exist
WARN[0000] could not initialize SBD collector: '/usr/sbin/sbd' does not exist
INFO[0000] DRBD collector registered
INFO[0000] Serving metrics on 0.0.0.0:9664
WARN[0015] Error while retrieving drbd infos exit status 20
WARN[0017] Error while retrieving drbd infos exit status 20
WARN[0019] Error while retrieving drbd infos exit status 20
WARN[0022] Error while retrieving drbd infos exit status 20 
WARN[0024] Error while retrieving drbd infos exit status 20

**Comment by MalloZup** [comment]
@kilida2020 hey thx for your issue.
Can you write it in english?
 I cannot full understand.

what linux operating system are you using? Which version of OS and which version of drbd?
thx!

**Comment by kilida2020** [comment]
I am using Debian 10 buster, DRBD is at version 9.5.0.

Ha_cluster_exporter is unable to collect DRBD metrics.
Displays the error message below.

WARN[0015] Error while retrieving drbd infos exit status 20

**Comment by MalloZup** [comment]
@kilida2020 ok. the error you have is because the exporter cannot execute the cmmand. Afaik, we used 8.0 not 9.


can you execute this command ``` "/sbin/drbdsetup"``` `"status", "--json`?

where do you have the binary located ```drbdsetup```?

It could be that : 

- the binary is located in other path. -> you can change the configuration exporter to this path. see `--help` and doc

- it could be that the `drbdsetup` binary 9 has changed some flags.

Let me know and ping me for any info. TIA :rose:

**Comment by kilida2020** [comment]
Well, another question
Will it only work in version 8.0 or any version referring to 8.0, for example 8.4, 8.9?

**Comment by diegoakechi** [comment]
@kilida2020 Claryfing here...the project supports DRBD 9 and higher... DRBD 8 is not supported. @MalloZup has mixed the versions on his answer. 
As mentioned, the problem can be related with different binary paths, so can you check where is your `drbdsetup` binary located and check the output of the status command with --json output?

**Comment by kilida2020** [comment]
So Claryfing, the binaries are in / sbin / drbsetup, which is the default.
When checking out with --json, can you instruct me how to do that?

**Comment by diegoakechi** [comment]
@kilida2020 just execute the command as the example below and paste here the result:

```
vmdrbd01:~ # /sbin/drbdsetup status --json
[
{
  "name": "sapdata",
  "node-id": 1,
  "role": "Primary",
  "suspended": false,
  "write-ordering": "flush",
  "devices": [
    {
      "volume": 0,
      "minor": 1,
      "disk-state": "UpToDate",
      "client": false,
      "quorum": true,
      "size": 10483356,
      "read": 1412,
      "written": 1164928,
      "al-writes": 229,
      "bm-writes": 0,
      "upper-pending": 0,
      "lower-pending": 0
    } ],
  "connections": [
    {
      "peer-node-id": 2,
      "name": "vmdrbd02",
      "connection-state": "Connected", 
      "congested": false,
      "peer-role": "Secondary",
      "ap-in-flight": 0,
      "rs-in-flight": 0,
      "peer_devices": [
        {
          "volume": 0,
          "replication-state": "Established",
          "peer-disk-state": "UpToDate",
          "peer-client": false,
          "resync-suspended": "no",
          "received": 0,
          "sent": 1165032,
          "out-of-sync": 0,
          "pending": 0,
          "unacked": 0,
          "has-sync-details": false,
          "has-online-verify-details": false,
          "percent-in-sync": 100.00
        } ]
    } ]
}
]
```

**Comment by kilida2020** [comment]
You do not recognize this command. Have to install something else to run it

root@node1:/# /sbin/drbdsetup status --json
status: unrecognized option '--json'

USAGE: drbdsetup command device arguments options

Device is usually /dev/drbdX or /dev/drbd/X.

Commands are:
    primary             secondary           attach              disk-options        detach              connect             net-options         disconnect
    resize              resource-options    new-current-uuid    invalidate          invalidate-remote   pause-sync          resume-sync         suspend-io
    resume-io           outdate             verify              down                state               role                sh-status           cstate
    dstate              show-gi             get-gi              show                status              check-resize        events              events2
    wait-connect        wait-sync           new-resource        new-minor           del-minor           del-resource

To get more details about a command issue 'drbdsetup help cmd'.

root@node1:/#

**Comment by diegoakechi** [comment]
Hum... Seems your `drbdsetup` does not supports the json output. Not sure since when it is available. @nick-wang do you know on what patch set the `--json` was introduced?

**Comment by MalloZup** [comment]
@diegoakechi thx for support and clarification to @kilida2020 

@kilida2020  thx for help sofar!

Ok seems that your binary doesn't the `--json`flag as I have guessed.

Let's wait from Nick some info. Maybe you can patch the binary.

**Comment by kilida2020** [comment]
Hey Clarifying,
You can tell me which distribution and version you use that works and which version of DRBD and DRBD-UTILS

Thanks,

**Comment by diegoakechi** [comment]
@kilida2020 It works for sure on SLES and openSUSE. On the oldest version we have tested at SUSE we have the `drbd-utils` version 9.0.8.

Looking on the changelog of `drbd-utils` the --json options was introduced on version 8.9.8 (https://github.com/LINBIT/drbd-utils/blob/master/ChangeLog#L213) , so it should be available for you too. 
I recommend you to check if the Debian package you are using eventually has some flag disabling some features during build or if it really uses the source of the version 9.5.0.

**Comment by nick-wang** [comment]
@kilida2020 @diegoakechi is correct. "--json" support first introduced into drbd-utils since 8.9.8 (https://github.com/LINBIT/drbd-utils/commit/f04cb0f67b2e8264cb9b977aa2a46e10ac26c38e), though have polish/enhancement after.

**Comment by kilida2020** [comment]
OK @nickwang, obrigada pela inforamção, mas você sabe informar se esta implementação ocorreu também para o DRBD-UTILS para distribuíções Debian? Porque naõ está funcionando no Debian 10

**Comment by kilida2020** [comment]
ops,
OK @nickwang, thanks for the information, but do you know if this implementation has also occurred for DRBD-UTILS for Debian distributions? Because it is not working on Debian 10

**Comment by diegoakechi** [comment]
Hi @kilida2020,

The implementation was done on the code upstream, on the github project, so it should be available for any distribution. Sometimes, some features are disabled on the package build `.deb` or the package is using some old version of the code. You need to check what package are you using and from where it gets the source code.

------------------------- Portuguese Version
A implementacao foi feita no codigo upstream, presente no projeto do Github, entao deveria star disponivel para todas as distribuicoes. As vezes, algumas funcionalidades sao desabilitadas durante a compilacao do package (arquivos `.deb`) ou a package que voce esta utilizando utilize uma versao antiga do codigo fonte. Voce precisa checar qual package voce esta usando e de onde ela obtem o codigo fonte.

**Comment by diegoakechi** [comment]
@kilida2020 can you please check my last comment? If it is clear enough for you, I will close the issue.

**Comment by kilida2020** [comment]
Hi @diegoakechi,

I am using the sources of this site https://salsa.debian.org/ha-team/drbd-utils/-/tags/, it has all the versions, I have already tested several from 8.9.8, which includes the implementation of json according to the Changelog but to no avail. Can you test it out there and help me?

**Comment by nick-wang** [comment]
> I am using the sources of this site https://salsa.debian.org/ha-team/drbd-utils/-/tags/, it has all the versions, I have already tested several from 8.9.8, which includes the implementation of json according to the Changelog but to no avail. Can you test it out there and help me?

@kilida2020 The drbd-utils source code looks the same, but i am not sure how `deb` package it. (Didn't try DRBD on Debian before)
Could you list your DRBD kernel module version in your system as well? like `modinfo drbd`.

**Comment by kilida2020** [comment]
@ nick-wang, yes I use drbd in debian, but only the ha_cluster_exporter tool from Linbit is not working.
Following is the result of the modinfo drbd:
root@srvlabm:/home/master# modinfo drbd
filename:       /lib/modules/4.19.0-8-amd64/updates/drbd.ko
alias:          block-major-147-*
license:        GPL
version:        9.0.22-1
description:    drbd - Distributed Replicated Block Device v9.0.22-1
author:         Philipp Reisner <phil@linbit.com>, Lars Ellenberg <lars@linbit.c                                                                                        om>
srcversion:     52413FD39C4525CBE0A6B1C
depends:        libcrc32c
retpoline:      Y
name:           drbd
vermagic:       4.19.0-8-amd64 SMP mod_unload modversions
parm:           enable_faults:int
parm:           fault_rate:int
parm:           fault_count:int
parm:           fault_devs:int
parm:           disable_sendpage:bool
parm:           allow_oos:DONT USE! (bool)
parm:           minor_count:Approximate number of drbd devices (1-255) (uint)
parm:           usermode_helper:string
parm:           protocol_version_min:drbd_protocol_version

**Comment by nick-wang** [comment]
@kilida2020 The DRBD is new enough to have the `json` support. Just like Diego mentioned, more likely the feature is disabled in package build. While ha_cluster_exporter is using the `json` output to parser...

**Comment by diegoakechi** [comment]
Maybe @vvidic could give you a hint on how to get drbd-utils with the json output. @vvidic could you help us here?

**Comment by vvidic** [comment]
Can you give us:
```
$ dpkg -l drbd-utils
$ cat /proc/drbd
```

From what I can tell it checks the version in /proc/drbd and than executes the correct variant of drbdsetup. In my case:
```
# strace drbdsetup status --json
execve("/usr/sbin/drbdsetup", ["drbdsetup", "status", "--json"], 0x7ffe0b9e33b0 /* 15 vars */) = 0
...
openat(AT_FDCWD, "/proc/drbd", O_RDONLY) = 3
read(3, "version: 8.4.10 (api:1/proto:86-"..., 4095) = 74
execve("/lib/drbd/drbdsetup-84", ["drbdsetup", "status", "--json"], 0x7fffe44985b8 /* 15 vars */) = 0
...
write(2, "status: unrecognized option '--j"..., 37status: unrecognized option '--json'
```

**Comment by kilida2020** [comment]
@vvidic 

root@srvlabm:/home/master# dpkg -l drbd-utils
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Nome           Versão       Arquitectura Descrição
+++-==============-============-============-=============================================
rc  drbd-utils     9.5.0-1      amd64        RAID 1 over TCP/IP for Linux (user utilities)
root@srvlabm:/home/master#
root@srvlabm:/home/master# cat /proc/drbd
version: 8.4.10 (api:1/proto:86-101)
srcversion: 983FCB77F30137D4E127B83

 1: cs:Connected ro:Primary/Secondary ds:UpToDate/UpToDate C r-----
    ns:0 nr:0 dw:0 dr:0 al:0 bm:0 lo:0 pe:0 ua:0 ap:0 ep:1 wo:f oos:0
root@srvlabm:/home/master#
root@srvlabm:/home/master#
root@srvlabm:/home/master# drbdsetup status --json
status: unrecognized option '--json'

USAGE: drbdsetup command device arguments options

Device is usually /dev/drbdX or /dev/drbd/X.

Commands are:
    primary             secondary           attach              disk-options        detach              connect             net-options         disconnect
    resize              resource-options    new-current-uuid    invalidate          invalidate-remote   pause-sync          resume-sync         suspend-io
    resume-io           outdate             verify              down                state               role                sh-status           cstate
    dstate              show-gi             get-gi              show                status              check-resize        events              events2
    wait-connect        wait-sync           new-resource        new-minor           del-minor           del-resource

To get more details about a command issue 'drbdsetup help cmd'###

**Comment by vvidic** [comment]
Yes, so you still have the default drbd v8.4.10 module from Debian kernel loaded.

You need to unload it and load the new one with drbd 9 support.

**Comment by diegoakechi** [comment]
@vvidic thanks a lot.

**Comment by vvidic** [comment]
No problem, hope it helps :)

**Comment by MalloZup** [comment]
thx @vvidic  for feedback and help! :rocket: :green_heart:

**Comment by kilida2020** [comment]
@vvidic 

It worked, I downloaded the DRBD 9 Linux Kernel Driver, compiled and installed it and it worked.
Thank you so much for your help and patience.
Thank you all,

root@srvlabm:/home/master# drbdsetup status --json
[
{
  "name": "drbdMtz",
  "node-id": 0,
  "role": "Primary",
  "suspended": false,
  "write-ordering": "flush",
  "devices": [
    {
      "volume": 0,
      "minor": 1,
      "disk-state": "UpToDate",
      "client": false,
      "quorum": true,
      "size": 524271964,
      "read": 1572345,
      "written": 21634257,
      "al-writes": 520,
      "bm-writes": 0,
      "upper-pending": 0,
      "lower-pending": 0
    } ],
  "connections": [
    {
      "peer-node-id": 1,
      "name": "srvlabs",
      "connection-state": "Connected",
      "congested": false,
      "peer-role": "Secondary",
      "ap-in-flight": 0,
      "rs-in-flight": 0,
      "peer_devices": [
        {
          "volume": 0,
          "replication-state": "Established",
          "peer-disk-state": "UpToDate",
          "peer-client": false,
          "resync-suspended": "no",
          "received": 0,
          "sent": 497089,
          "out-of-sync": 0,
          "pending": 0,
          "unacked": 0,
          "has-sync-details": false,
          "has-online-verify-details": false,
          "percent-in-sync": 100.00
        } ]
    } ]
}
]

**Comment by vvidic** [comment]
Cool, thanks for the update :)

**Comment by diegoakechi** [comment]
Ok, so closing this issue.

**Comment by MalloZup** [comment]
thx!
