### ISSUE TITLE
error cibadm - debian 10 buster

### ISSUE THREAD

**Issue by kilida2020** [ClusterLabs/ha_cluster_exporter#146]
Hi,

I have the error below in the ha_cluster exporter, so the metrics of Pacemaker are not being exported,
Can you check what can cause this type of error?

WARN [0006] could not parse cibadmin status from XML: strconv.ParseInt: parsing "29s": invalid syntax

Thanks,

**Comment by diegoakechi** [comment]
@kilida2020 hi,

This looks really similar to https://github.com/ClusterLabs/ha_cluster_exporter/issues/138

Are you using the latest version of the exporter? If yes, can you share the CIB XML that you have on your cluster?

**Comment by kilida2020** [comment]
You're right, I'm sorry, my version was old, I updated it and the bug was fixed.
However you are now displaying the message below and the metrics for corosync ring errors are not collected

WARN [0095] cannot parse ring status: corosync-cfgtool returned unexpected output: Printing link status.
Local node ID 2
LINK ID 0
         addr = 128.1.0.87
         status = OK

**Comment by diegoakechi** [comment]
@kilida2020 Ok, just to have a better organization, I will close this issue. Can you open a new one for the corosync error? Please, run the exporter on debug mode and include the extra messages on the new ticket too.

Thanks.

**Comment by kilida2020** [comment]
OK no problems.
Just instruct me how to run in debugger mode, please.

Thanks,

**Comment by MalloZup** [comment]
@kilida2020 

```
# ha_cluster_exporter -h
Usage of ha_cluster_exporter:
      --address string                     The address to listen on for HTTP requests (default "0.0.0.0")
      --cibadmin-path string               path to cibadmin executable (default "/usr/sbin/cibadmin")
      --corosync-cfgtoolpath-path string   path to corosync-cfgtool executable (default "/usr/sbin/corosync-cfgtool")
      --corosync-quorumtool-path string    path to corosync-quorumtool executable (default "/usr/sbin/corosync-quorumtool")
      --crm-mon-path string                path to crm_mon executable (default "/usr/sbin/crm_mon")
      --drbdsetup-path string              path to drbdsetup executable (default "/sbin/drbdsetup")
      --drbdsplitbrain-path string         path to drbd splitbrain hooks temporary files (default "/var/run/drbd/splitbrain")
      --enable-timestamps                  Add the timestamp to every metric line (hint: don't do this unless you really know what you are doing)
      --log-level string                   The minimum logging level; levels are, in ascending order: debug, info, warn, error (default "info")
      --port string                        The port number to listen on for HTTP requests (default "9664")
      --sbd-config-path string             path to sbd configuration (default "/etc/sysconfig/sbd")
      --sbd-path string                    path to sbd executable (default "/usr/sbin/sbd")
```

``` ha_cluster_exporter -log-level debug
```
