### ISSUE TITLE
Sample Prometheus alerting rules

### ISSUE THREAD

**Issue by cameronkerrnz** [ClusterLabs/ha_cluster_exporter#155]
Hello, I am interested in using your exporter to help monitor my two-node cluster that has DRBD version 9 with a master-slave relationship, a floating IP and filesystem and a MariaDB systemd service managed by pacemaker. I was particularly happy to see that you have DRBD version 9 support.

I've had one failure mode that I've encountered thus far caused by a matching kernel module that was missing after a kernel update that lead to a split-brain scenario. My experience with Pacemaker thus far has only been a couple of two-node clusters on CentOS.

Do you have any prometheus alerting rules you could share as a starting point?

Thanks,
Cameron

**Comment by MalloZup** [comment]
@cameronkerrnz hi thx for you issue.
Yes, we place the alerts here: https://github.com/SUSE/ha-sap-terraform-deployments/blob/master/salt/monitoring/prometheus/rules.yml

Also we have the dashboards grafana here:

https://github.com/SUSE/ha-sap-terraform-deployments/tree/master/salt/monitoring/provisioning/dashboards
As note, this are alerts as "showcase" so some adaption might needed.

Let me know.

we might have to improve the doc on this regards.

For any question feel free to ask

**Comment by cameronkerrnz** [comment]
Thanks!

**Comment by pascal-hofmann** [comment]
See https://github.com/SUSE/ha-sap-terraform-deployments/blob/38741a5df939ff2d953457ec72c1a1e22efb6529/salt/monitoring_srv/prometheus/rules.yml#L42
