### ISSUE TITLE
Error when disabled all cluster nodes

### ISSUE THREAD

**Issue by damianw2** [ClusterLabs/ha_cluster_exporter#193]
OS: SUSE Enterprise 15.1

Steps to reproduce:
Run the command:  crm resource stop rsc_DB_A02
db00:/ # crm status

Clone Set: msl_DB_A02 [rsc_DB_A02] (promotable)

     Stopped (disabled): [ db00 db01 ]
An error has occurred while serving metrics:

5 error(s) occurred:

* collected metric "ha_cluster_pacemaker_resources" { label:<name:"agent" value:"ocf::suse:DB" > label:<name:"clone" value:"msl_DB_A02" > label:<name:"group" value:"" > label:<name:"managed" value:"true" > label:<name:"node" value:"" > label:<name:"resource" value:"rsc_DB_A02" > label:<name:"role" value:"stopped" > label:<name:"status" value:"orphaned" > gauge:<value:0 > } was collected before with the same name and label values

* collected metric "ha_cluster_pacemaker_resources" { label:<name:"agent" value:"ocf::suse:DB" > label:<name:"clone" value:"msl_DB_A02" > label:<name:"group" value:"" > label:<name:"managed" value:"true" > label:<name:"node" value:"" > label:<name:"resource" value:"rsc_DB_A02" > label:<name:"role" value:"stopped" > label:<name:"status" value:"blocked" > gauge:<value:0 > } was collected before with the same name and label values

* collected metric "ha_cluster_pacemaker_resources" { label:<name:"agent" value:"ocf::suse:DB" > label:<name:"clone" value:"msl_DB_A02" > label:<name:"group" value:"" > label:<name:"managed" value:"true" > label:<name:"node" value:"" > label:<name:"resource" value:"rsc_DB_A02" > label:<name:"role" value:"stopped" > label:<name:"status" value:"failed" > gauge:<value:0 > } was collected before with the same name and label values

* collected metric "ha_cluster_pacemaker_resources" { label:<name:"agent" value:"ocf::suse:DB" > label:<name:"clone" value:"msl_DB_A02" > label:<name:"group" value:"" > label:<name:"managed" value:"true" > label:<name:"node" value:"" > label:<name:"resource" value:"rsc_DB_A02" > label:<name:"role" value:"stopped" > label:<name:"status" value:"failure_ignored" > gauge:<value:0 > } was collected before with the same name and label values

* collected metric "ha_cluster_pacemaker_resources" { label:<name:"agent" value:"ocf::suse:DB" > label:<name:"clone" value:"msl_DB_A02" > label:<name:"group" value:"" > label:<name:"managed" value:"true" > label:<name:"node" value:"" > label:<name:"resource" value:"rsc_DB_A02" > label:<name:"role" value:"stopped" > label:<name:"status" value:"active" > gauge:<value:0 > } was collected before with the same name and label values

**Comment by stefanotorresi** [comment]
Hey there!
Could you please paste the output of `crm_mon -X --inactive`?

**Comment by damianw2** [comment]
Hi,
I'm pasting from different cluster with the same problem:
hana01:~ # crm_mon -X --inactive
<?xml version="1.0"?>
<crm_mon version="2.0.1">
    <summary>
        <stack type="corosync" />
        <current_dc present="true" version="2.0.1+20190417.13d370ca9-3.15.1-2.0.1+20190417.13d370ca9" name="hana00" id="1" with_quorum="true" />
        <last_update time="Wed May 26 13:25:03 2021" />
        <last_change time="Wed May 26 13:25:00 2021" user="root" client="crm_attribute" origin="hana00" />
        <nodes_configured number="2" />
        <resources_configured number="10" disabled="2" blocked="0" />
        <cluster_options stonith-enabled="true" symmetric-cluster="true" no-quorum-policy="stop" maintenance-mode="false" />
    </summary>
    <nodes>
        <node name="hana00" id="1" online="true" standby="false" standby_onfail="false" maintenance="false" pending="false" unclean="false" shutdown="false" expected_up="true" is_dc="true" resources_running="4" type="member" />
        <node name="hana01" id="2" online="true" standby="false" standby_onfail="false" maintenance="false" pending="false" unclean="false" shutdown="false" expected_up="true" is_dc="false" resources_running="3" type="member" />
    </nodes>
    <resources>
        <resource id="rsc_st_azure" resource_agent="stonith:fence_azure_arm" role="Stopped" active="false" orphaned="false" blocked="false" managed="true" failed="false" failure_ignored="false" nodes_running_on="0" />
        <clone id="cln_azure-events" multi_state="false" unique="false" managed="true" failed="false" failure_ignored="false" >
            <resource id="rsc_azure-events" resource_agent="ocf::heartbeat:azure-events" role="Started" active="true" orphaned="false" blocked="false" managed="true" failed="false" failure_ignored="false" nodes_running_on="1" >
                <node name="hana00" id="1" cached="false"/>
            </resource>
            <resource id="rsc_azure-events" resource_agent="ocf::heartbeat:azure-events" role="Started" active="true" orphaned="false" blocked="false" managed="true" failed="false" failure_ignored="false" nodes_running_on="1" >
                <node name="hana01" id="2" cached="false"/>
            </resource>
        </clone>
        <resource id="stonith-sbd" resource_agent="stonith:external/sbd" role="Started" active="true" orphaned="false" blocked="false" managed="true" failed="false" failure_ignored="false" nodes_running_on="1" >
            <node name="hana01" id="2" cached="false"/>
        </resource>
        <clone id="cln_SAPHanaTopology_A02" multi_state="false" unique="false" managed="true" failed="false" failure_ignored="false" >
            <resource id="rsc_SAPHanaTopology_A02" resource_agent="ocf::suse:SAPHanaTopology" role="Started" active="true" orphaned="false" blocked="false" managed="true" failed="false" failure_ignored="false" nodes_running_on="1" >
                <node name="hana00" id="1" cached="false"/>
            </resource>
            <resource id="rsc_SAPHanaTopology_A02" resource_agent="ocf::suse:SAPHanaTopology" role="Started" active="true" orphaned="false" blocked="false" managed="true" failed="false" failure_ignored="false" nodes_running_on="1" >
                <node name="hana01" id="2" cached="false"/>
            </resource>
        </clone>
        <clone id="msl_SAPHana_A02" multi_state="true" unique="false" managed="true" failed="false" failure_ignored="false" target_role="Stopped" >
            <resource id="rsc_SAPHana_A02" resource_agent="ocf::suse:SAPHana" role="Stopped" target_role="Stopped" active="false" orphaned="false" blocked="false" managed="true" failed="false" failure_ignored="false" nodes_running_on="0" />
            <resource id="rsc_SAPHana_A02" resource_agent="ocf::suse:SAPHana" role="Stopped" target_role="Stopped" active="false" orphaned="false" blocked="false" managed="true" failed="false" failure_ignored="false" nodes_running_on="0" />
        </clone>
        <group id="g_ip_A02" number_resources="2" >
             <resource id="rsc_ip_A02" resource_agent="ocf::heartbeat:IPaddr2" role="Started" active="true" orphaned="false" blocked="false" managed="true" failed="false" failure_ignored="false" nodes_running_on="1" >
                 <node name="hana00" id="1" cached="false"/>
             </resource>
             <resource id="rsc_nc_A02" resource_agent="ocf::heartbeat:anything" role="Started" active="true" orphaned="false" blocked="false" managed="true" failed="false" failure_ignored="false" nodes_running_on="1" >
                 <node name="hana00" id="1" cached="false"/>
             </resource>
        </group>
    </resources>
    <node_attributes>
        <node name="hana00">
            <attribute name="azName" value="DWhana02-HANA-HN1-VM" />
            <attribute name="hana_a02_clone_state" value="UNDEFINED" />
            <attribute name="hana_a02_op_mode" value="logreplay" />
            <attribute name="hana_a02_remoteHost" value="hana01" />
            <attribute name="hana_a02_roles" value="1:P:master1::worker:" />
            <attribute name="hana_a02_site" value="Site1" />
            <attribute name="hana_a02_srmode" value="sync" />
            <attribute name="hana_a02_sync_state" value="PRIM" />
            <attribute name="hana_a02_vhost" value="hana00" />
            <attribute name="lpa_a02_lpt" value="1622033992" />
            <attribute name="master-rsc_SAPHana_A02" value="150" />
        </node>
        <node name="hana01">
            <attribute name="azName" value="DWhana02-HANA-HN2-VM" />
            <attribute name="hana_a02_clone_state" value="UNDEFINED" />
            <attribute name="hana_a02_op_mode" value="logreplay" />
            <attribute name="hana_a02_remoteHost" value="hana00" />
            <attribute name="hana_a02_roles" value="1:S:master1::worker:" />
            <attribute name="hana_a02_site" value="Site2" />
            <attribute name="hana_a02_srmode" value="sync" />
            <attribute name="hana_a02_sync_state" value="SOK" />
            <attribute name="hana_a02_vhost" value="hana01" />
            <attribute name="lpa_a02_lpt" value="10" />
            <attribute name="master-rsc_SAPHana_A02" value="100" />
        </node>
    </node_attributes>
    <node_history>
        <node name="hana00">
            <resource_history id="rsc_st_azure" orphan="false" migration-threshold="5000" fail-count="1000000" last-failure="Tue May 25 22:47:37 2021">
                <operation_history call="14" task="start" last-rc-change="Tue May 25 22:47:31 2021" last-run="Tue May 25 22:47:31 2021" exec-time="6235ms" queue-time="0ms" rc="1" rc_text="unknown error" />
                <operation_history call="16" task="stop" last-rc-change="Tue May 25 22:47:37 2021" last-run="Tue May 25 22:47:37 2021" exec-time="0ms" queue-time="0ms" rc="0" rc_text="ok" />
            </resource_history>
            <resource_history id="rsc_azure-events" orphan="false" migration-threshold="5000">
                <operation_history call="13" task="probe" last-rc-change="Tue May 25 22:46:40 2021" last-run="Tue May 25 22:46:40 2021" exec-time="50334ms" queue-time="0ms" rc="0" rc_text="ok" />
                <operation_history call="13" task="probe" last-rc-change="Tue May 25 22:46:40 2021" last-run="Tue May 25 22:46:40 2021" exec-time="50334ms" queue-time="0ms" rc="0" rc_text="ok" />
                <operation_history call="35" task="monitor" interval="10000ms" last-rc-change="Tue May 25 23:29:06 2021" exec-time="312ms" queue-time="0ms" rc="0" rc_text="ok" />
            </resource_history>
            <resource_history id="rsc_SAPHanaTopology_A02" orphan="false" migration-threshold="5000">
                <operation_history call="37" task="start" last-rc-change="Tue May 25 23:29:06 2021" last-run="Tue May 25 23:29:06 2021" exec-time="3460ms" queue-time="0ms" rc="0" rc_text="ok" />
                <operation_history call="43" task="monitor" interval="10000ms" last-rc-change="Tue May 25 23:29:10 2021" exec-time="3409ms" queue-time="0ms" rc="0" rc_text="ok" />
            </resource_history>
            <resource_history id="rsc_SAPHana_A02" orphan="false" migration-threshold="5000">
                <operation_history call="26" task="probe" last-rc-change="Tue May 25 23:28:29 2021" last-run="Tue May 25 23:28:29 2021" exec-time="3101ms" queue-time="0ms" rc="0" rc_text="ok" />
                <operation_history call="55" task="monitor" interval="60000ms" last-rc-change="Tue May 25 23:29:21 2021" exec-time="2872ms" queue-time="1ms" rc="8" rc_text="master" />
                <operation_history call="61" task="stop" last-rc-change="Wed May 26 13:00:08 2021" last-run="Wed May 26 13:00:08 2021" exec-time="50980ms" queue-time="0ms" rc="0" rc_text="ok" />
            </resource_history>
            <resource_history id="rsc_ip_A02" orphan="false" migration-threshold="5000">
                <operation_history call="36" task="start" last-rc-change="Tue May 25 23:29:06 2021" last-run="Tue May 25 23:29:06 2021" exec-time="79ms" queue-time="0ms" rc="0" rc_text="ok" />
                <operation_history call="40" task="monitor" interval="10000ms" last-rc-change="Tue May 25 23:29:06 2021" exec-time="62ms" queue-time="0ms" rc="0" rc_text="ok" />
            </resource_history>
            <resource_history id="rsc_nc_A02" orphan="false" migration-threshold="5000">
                <operation_history call="41" task="start" last-rc-change="Tue May 25 23:29:06 2021" last-run="Tue May 25 23:29:06 2021" exec-time="138ms" queue-time="1ms" rc="0" rc_text="ok" />
                <operation_history call="45" task="monitor" interval="10000ms" last-rc-change="Tue May 25 23:29:10 2021" exec-time="14ms" queue-time="0ms" rc="0" rc_text="ok" />
            </resource_history>
        </node>
        <node name="hana01">
            <resource_history id="stonith-sbd" orphan="false" migration-threshold="5000">
                <operation_history call="15" task="start" last-rc-change="Tue May 25 22:47:31 2021" last-run="Tue May 25 22:47:31 2021" exec-time="1340ms" queue-time="1ms" rc="0" rc_text="ok" />
                <operation_history call="39" task="monitor" interval="15000ms" last-rc-change="Tue May 25 23:29:06 2021" exec-time="1343ms" queue-time="1ms" rc="0" rc_text="ok" />
            </resource_history>
            <resource_history id="rsc_st_azure" orphan="false" migration-threshold="5000" fail-count="1000000" last-failure="Tue May 25 22:47:43 2021">
                <operation_history call="17" task="start" last-rc-change="Tue May 25 22:47:37 2021" last-run="Tue May 25 22:47:37 2021" exec-time="6168ms" queue-time="0ms" rc="1" rc_text="unknown error" />
                <operation_history call="18" task="stop" last-rc-change="Tue May 25 22:47:43 2021" last-run="Tue May 25 22:47:43 2021" exec-time="0ms" queue-time="0ms" rc="0" rc_text="ok" />
            </resource_history>
            <resource_history id="rsc_azure-events" orphan="false" migration-threshold="5000">
                <operation_history call="13" task="probe" last-rc-change="Tue May 25 22:46:41 2021" last-run="Tue May 25 22:46:41 2021" exec-time="40402ms" queue-time="0ms" rc="0" rc_text="ok" />
                <operation_history call="13" task="probe" last-rc-change="Tue May 25 22:46:41 2021" last-run="Tue May 25 22:46:41 2021" exec-time="40402ms" queue-time="0ms" rc="0" rc_text="ok" />
                <operation_history call="38" task="monitor" interval="10000ms" last-rc-change="Tue May 25 23:29:06 2021" exec-time="294ms" queue-time="0ms" rc="0" rc_text="ok" />
            </resource_history>
            <resource_history id="rsc_SAPHanaTopology_A02" orphan="false" migration-threshold="5000">
                <operation_history call="40" task="start" last-rc-change="Tue May 25 23:29:06 2021" last-run="Tue May 25 23:29:06 2021" exec-time="3196ms" queue-time="1ms" rc="0" rc_text="ok" />
                <operation_history call="43" task="monitor" interval="10000ms" last-rc-change="Tue May 25 23:29:10 2021" exec-time="3759ms" queue-time="0ms" rc="0" rc_text="ok" />
            </resource_history>
            <resource_history id="rsc_SAPHana_A02" orphan="false" migration-threshold="5000">
                <operation_history call="29" task="probe" last-rc-change="Tue May 25 23:28:29 2021" last-run="Tue May 25 23:28:29 2021" exec-time="3949ms" queue-time="0ms" rc="0" rc_text="ok" />
                <operation_history call="44" task="monitor" interval="61000ms" last-rc-change="Tue May 25 23:29:10 2021" exec-time="2965ms" queue-time="0ms" rc="0" rc_text="ok" />
                <operation_history call="53" task="stop" last-rc-change="Wed May 26 13:00:08 2021" last-run="Wed May 26 13:00:08 2021" exec-time="20844ms" queue-time="1ms" rc="0" rc_text="ok" />
            </resource_history>
        </node>
    </node_history>
    <failures>
        <failure op_key="rsc_st_azure_start_0" node="hana00" exitstatus="unknown error" exitreason="" exitcode="1" call="14" status="complete" last-rc-change="Tue May 25 22:47:31 2021" queued="0" exec="6235" interval="0" task="start" />
        <failure op_key="rsc_st_azure_start_0" node="hana01" exitstatus="unknown error" exitreason="" exitcode="1" call="17" status="complete" last-rc-change="Tue May 25 22:47:37 2021" queued="0" exec="6168" interval="0" task="start" />
    </failures>
    <fence_history>
    </fence_history>
    <tickets>
    </tickets>
    <bans>
    </bans>
</crm_mon>

**Comment by damianw2** [comment]
@stefanotorresi any update on this? We are blocked becuse of that issue.

**Comment by diegoakechi** [comment]
HI @damianw2,

Please, be aware that we provide support here on a community opensource basis, which might not fulfill your internal solutions SLAs. 
If this is a production environment and demands SLAs for a solution, please refer to your OS vendor support process in order to receive an faster response.

**Comment by stefanotorresi** [comment]
@damianw2 I think I understood where the problem lies. Will work on a fix soon.

**Comment by stefanotorresi** [comment]
@damianw2 could you please try this binary: https://github.com/ClusterLabs/ha_cluster_exporter/suites/2848129495/artifacts/63570802
and tell me if it works or not?

**Comment by damianw2** [comment]
@diegoakechi I am aware about your opensource project support and don't expect any SLA ;) I only want to know if the issue is complicated and I should engage my team or you can fix it easily. 

@stefanotorresi your new binary is working fine, thanks a lot! Good job! I haven't expect so quick fix, impressive!
