### ISSUE TITLE
Not able to install Latest 1.3.0 version for prometheus-ha_cluster_exporter

### ISSUE THREAD

**Issue by DhruvSehgal** [ClusterLabs/ha_cluster_exporter#204]
Hi, I am trying to install latest version (1.3.0) for prometheus-ha_cluster_exporter on SUSE. (Need to test TLS support feature added to 1.3.0 version)

I used following command: 
sudo zypper install prometheus-ha_cluster_exporter

But it is unable to find higer version than 1.2.3.
<img width="782" alt="image" src="https://user-images.githubusercontent.com/89583381/192706996-590dec04-c9bb-4a1d-934a-c775a9b749f1.png">

I am using opensuse-leap 15.4, and sles-sap-15-sp3 vm images on azure for the same.

Please let me know if there is any way to force install the latest version on my vm.
Would be happy to help if any other detail is required from my end.

Thanks,
Dhruv

**Comment by ajaeger** [comment]
Hi Dhruv, this has not been released yet, it's on it's way to maintenance, QA and will then be available. If you need it urgently, please tell me and we'll find a way to share a pre-release.

**Comment by DhruvSehgal** [comment]
Hi ajaeger, Thanks for quick reply.

Wanted to get a timeline on when this feature would be shipped.

**Comment by ajaeger** [comment]
It is currently in the QA queue, should be out any day now.

**Comment by ajaeger** [comment]
@DhruvSehgal , it's out - see https://lists.suse.com/pipermail/sle-updates/2022-October/025530.html
