### ISSUE TITLE
regexp parsing corosync-cfgtool output will not work

### ISSUE THREAD

**Issue by linuxnase** [ClusterLabs/ha_cluster_exporter#215]
In collector/corosync/parser.go line 154
There is a bug in the regexp when parsing corosync-cfgtool -s output:
```re := regexp.MustCompile(`(?m)(?P<prefix>RING|Link) ID (?P<number>\d+)\s+(?P<id>id|addr) \s*= (?P<address>.+)\s+status \s*= (?P<status>.+)`)```
corosync-cfgtool outputs a tab character after "id" and "status", so the regexp with an additional space after id/status will not match. Without the spaces in front of "\s" the regexp will work. 
```...(?P<id>id|addr)\s*= (?P<address>.+)\s+status\s*=...```

**Comment by stefanotorresi** [comment]
hey, thanks for reporting this! It should now be fixed, could you please confirm that by building from the latest sources?
