### ISSUE TITLE
No instance id inside export metrics

### ISSUE THREAD

**Issue by sadon** [ClusterLabs/ha_cluster_exporter#240]
Almost all of metrics have no 'instance' inside exported metrics as result default dashboards stay unusable.

![image](https://github.com/ClusterLabs/ha_cluster_exporter/assets/2854508/0da30a32-c67f-40b0-acaf-809876b088bb)

example **Online nodes** query: 
`count(ha_cluster_pacemaker_nodes{instance="", status="online"} == 1) / count(count(ha_cluster_pacemaker_nodes{instance=""}) by (node))`

Exporter:
````
curl localhost:9664/metrics -s | grep "ha_cluster_pacemaker_nodes"
# HELP ha_cluster_pacemaker_nodes The status of each node in the cluster; 1 means the node is in that status, 0 otherwise
# TYPE ha_cluster_pacemaker_nodes gauge
ha_cluster_pacemaker_nodes{node="dc-test-pg-01",status="dc",type="member"} 1
ha_cluster_pacemaker_nodes{node="dc-test-pg-01",status="expected_up",type="member"} 1
ha_cluster_pacemaker_nodes{node="dc-test-pg-01",status="maintenance",type="member"} 0
ha_cluster_pacemaker_nodes{node="dc-test-pg-01",status="online",type="member"} 1
````

**Comment by stefanotorresi** [comment]
There has never been any "instance" label in any of the metrics. Where does this expectation come from?
