### ISSUE TITLE
Running as non-root user

### ISSUE THREAD

**Issue by ColmMcBarron** [ClusterLabs/ha_cluster_exporter#242]
How should this be setup to run as a non root user with read only access?

A  sudo user with access to the binaries returns a lot of permissions errors.

```
level=warn msg="pacemaker collector scrape failed"
level=warn msg="corosync collector scrape failed"
```
Running the raw commands for cfgtool also throw an error.

Running it as root works fine.

I am guessing there are some underlying binaries that need to be added to the sudoers file?

Maybe this is a documentation problem.

**Comment by ThomasG77** [comment]
You may look at https://docs.goreplay.org/untitled/running-as-non-root-user

**Comment by stefanotorresi** [comment]
> Running the raw commands for cfgtool also throw an error.

If running the raw commands throws an error, then the upstream tool needs to support sudo usage in the first place, there is not much we can do in the exporter; we just consume those tools, and they assume root, the exporter needs to do so as well.
