### ISSUE TITLE
kernel: Unknown VPD Code: 0x89

### ISSUE THREAD

**Issue by wtmpx** [ClusterLabs/ha_cluster_exporter#244]
On my ISCSI system I see a lot of similar messages: 

Feb 15 11:31:27 aaiscsisrv kernel: Unknown VPD Code: 0x89
Feb 15 11:31:42 aaiscsisrv kernel: Unknown VPD Code: 0x89
Feb 15 11:31:57 aaiscsisrv kernel: Unknown VPD Code: 0x89
Feb 15 11:32:12 aaiscsisrv kernel: Unknown VPD Code: 0x89

these messages being written each 25 seconds.  Once I stop prometheus-ha_cluster_exporter service, these messages stop.

**Comment by wtmpx** [comment]
The correct way to deal with this kind of error is to send and INQUIRY for page 0 first (sg_inq), to obtain the list of supported VPD pages, and check if the desired page is in the list. Repeating this kind of inquiry every few seconds doesn't make sense at all.

**Comment by stefanotorresi** [comment]
We don't do anything with ISCSI in the exporter, I have no idea how to correlate the two things.

**Comment by wtmpx** [comment]
The disk was used as SBD device.

**Comment by wtmpx** [comment]
The sbd ... dump and list triggers these messages.
