### ISSUE TITLE
Need help with building the rpm for RHEL 9 and derivatives

### ISSUE THREAD

**Issue by hunter86bg** [ClusterLabs/ha_cluster_exporter#251]
Hi,

Can I get the SPEC file and a description of the dependencies in order to build the rpm for RHEL9 (Rocky9,OEL9, etc) ?

**Comment by stefanotorresi** [comment]
there are no particular requirements other than a reasonably recent Go compiler. You can look at the spec for SUSE here:
https://github.com/ClusterLabs/ha_cluster_exporter/blob/main/packaging/obs/prometheus-ha_cluster_exporter/prometheus-ha_cluster_exporter.spec
