### ISSUE TITLE
Bug / Feature Request: Cluster SBD Error'ing (when not present)

### ISSUE THREAD

**Issue by ashleyprimo** [ClusterLabs/ha_cluster_exporter#28]
I have noticed that when operating the exporter on a machine that does not have `sbd` setup the following set of errors are seen repeatedly:

```
2019/10/11 15:14:12 [INFO]: Reading cluster SBD configuration..
2019/10/11 15:14:12 [ERROR] Could not open sbd config file open /etc/sysconfig/sbd: no such file or directory
```

There should maybe be a check such as 

```
if _, err := os.Stat("/etc/sysconfig/sbd"); os.IsNotExist(err) {
	log.Println("[INFO]: SBD is not present... skipping.")
} else {

}
```

This would give a single output of `0000/00/00 00:00:00 [INFO]: SBD is not present... skipping.` instead of continually repeating an error in the absence of sbd. :)

**Comment by MalloZup** [comment]
done

**Comment by MalloZup** [comment]
thx!
