### ISSUE TITLE
Create Index in Readme.md

### ISSUE THREAD

**Issue by MalloZup** [ClusterLabs/ha_cluster_exporter#38]
we should have an index in Markdown for each central point.

**Comment by Nikhil-Vats** [comment]
Hey, correct me if I am wrong - Do you just need a table of contents with central points pointing to each section? If yes, I will send a PR tomorrow.

**Comment by MalloZup** [comment]
@Nikhil-Vats yes thx!

**Comment by Nikhil-Vats** [comment]
@MalloZup PR sent, let me know if I missed something.
