### ISSUE TITLE
update readme description

### ISSUE THREAD

**Issue by MalloZup** [ClusterLabs/ha_cluster_exporter#39]
# Desc
the readme contain an outdated text:

`This prometheus exporter is used to serve metrics for pacemaker https://github.com/ClusterLabs/pacemaker. It should run inside a node of the cluster or both.`

We now export more metrics like SBD, drbd and other components.

We should write a more generic description for this.

An example would be: (it might need improvement and research)

 Like the exporter is used to serve metrics for ha clusters and their components. 
As second usage will be that, the exporter is intented to work also as only exporter for a single component, in this case it will just serve the metrics for this compenent

**Comment by paulo-filho-dev** [comment]
@MalloZup I can help on this one

**Comment by MalloZup** [comment]
thx
