### ISSUE TITLE
easy-fix / testing:  expand current test for pacemaker

### ISSUE THREAD

**Issue by MalloZup** [ClusterLabs/ha_cluster_exporter#49]
# description: 

the following file has some unit-tests. https://github.com/ClusterLabs/ha_cluster_exporter/blob/master/pacemaker_metrics_test.go#L76

It would be nice to extend this tests following same pattern Just testing other attirbutes.

**Comment by mbiagetti** [comment]
Can I work on it?

**Comment by MalloZup** [comment]
Yes feel free
