### ISSUE TITLE
EASY-FIX: Add go fmt check in travis

### ISSUE THREAD

**Issue by MalloZup** [ClusterLabs/ha_cluster_exporter#57]
we should add a check in travis to check that golang code is properly formatted.

**Comment by sathia27** [comment]
@MalloZup I would like to contribute.

Few questions.
Makefile already have `go fmt` and we call that in travis. What new check to be added as part of this issue?

**Comment by MalloZup** [comment]
@sathia27 thx feel free to contribute. :rocket: 

The `go fmt` will not fail in makefile. So example: if I do a wrong indentation, the `go fmt` will just format it but not fail.

We need a target like `travis-lint` which will check if the golang files are formatted well and fail if it is the case.

Currently the go fmt is more a target for local dev.

When I run `make` this clean automatically.

Feel free tor raise any question

**Comment by sathia27** [comment]
@MalloZup 
Thanks for your brief explanation.
I have given PR, please let me know if I something needs to be changed.
