### ISSUE TITLE
differentiate node type and status

### ISSUE THREAD

**Issue by MalloZup** [ClusterLabs/ha_cluster_exporter#62]
#  Desc
From metric `ha_cluster_nodes`
differentiate node "type" and "status":
type: member/remote
status: combinations of "online/standby/standby_onfail/maintenance/pending/unclean/shutdown/expected_up/is_dc".

follow-up from 
https://github.com/ClusterLabs/ha_cluster_exporter/pull/58#discussion_r335948005

**Comment by stefanotorresi** [comment]
implemented in #66 as documented in https://github.com/ClusterLabs/ha_cluster_exporter/blob/master/doc/metric_spec.md#ha_cluster_pacemaker_nodes
