### ISSUE TITLE
DOC: find a way to generate documentation automatically and write other things manually

### ISSUE THREAD

**Issue by MalloZup** [ClusterLabs/ha_cluster_exporter#63]
# Description:

This issue is after discussion with me, @diegoakechi and @stefanotorresi.

We agreed that we should find a compromise between generating docs automatically and maintain them manually.

# Tasks:
- [ ] research and investigate what we can automatically create (Name of metric, HELP etc, list)

This task might depend also if we want to refactor the exporter with the usage of collector, which will change a bit the API so also the automatic generation can be impacted. We should then wait a little before doing this

**Comment by stefanotorresi** [comment]
Since the skeleton in [doc/metric_spec.md](../blob/master/doc/metric_spec.md) reached a good enough compromise by linking to the `.metrics` fixture files used to test the collectors, I'd say we can close this issue, do you agree?

**Comment by MalloZup** [comment]
yes we don't need to mantain complicated automation process. closing awesome
