### ISSUE TITLE
Feature Request: Implement a landing page

### ISSUE THREAD

**Issue by ashleyprimo** [ClusterLabs/ha_cluster_exporter#69]
Currently, if you visit the exporter on `http://localhost:9002/` you get a `404` error, which is not an issue per se, however, would be nice to have a simple landing page which just explains what the exporter is- similar to various others such as node exporter.

This could be done using something such as:
```
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte(`<html>
			<head>
				<title>HACluster Exporter</title>
			</head>
			<body>
				<h1>HACluster Exporter</h1>
				<p><a href="/metrics">Metrics</a></p>
                                <br />
				<h2>More information:</h2>
				<p><a href="https://github.com/ClusterLabs/ha_cluster_exporter">github.com/ClusterLabs/ha_cluster_exporter</a></p>
			</body>
			</html>`))
	})

```

**Comment by MalloZup** [comment]
I'm ok to mimic it thx for issue ! @stefanotorresi opinions?

**Comment by MalloZup** [comment]
done thx
