### ISSUE TITLE
Add changelog file

### ISSUE THREAD

**Issue by MalloZup** [ClusterLabs/ha_cluster_exporter#85]
discuss which format take fro changelog  and add one if needed

**Comment by MalloZup** [comment]
taking this right now

**Comment by stefanotorresi** [comment]
I'm wondering if we should just rely on GH releases and forget about this. What do you think @MalloZup ?

**Comment by MalloZup** [comment]
@stefanotorresi yep I agree we can forget for moment on this. THere is not high pressure
